--- #YAML:1.0
name:               Validator-Custom-HTMLForm
version:            0.0611
abstract:           HTML Form Validator
author:
    - Yuki Kimoto <kimoto.yuki@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Calc:           5.4
    DateTime::Format::Strptime:  1.07
    Email::Valid:         0.15
    Email::Valid::Loose:  0.04
    Test::More:           0
    Time::Piece:          1.15
    Validator::Custom:    0.1208
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
