---
abstract: DEPRECATED!
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Validator-Custom-HTMLForm
provides:
  Validator::Custom::HTMLForm:
    file: lib/Validator/Custom/HTMLForm.pm
    version: 0.0612
  Validator::Custom::HTMLForm::Constraints:
    file: lib/Validator/Custom/HTMLForm/Constraints.pm
requires:
  Date::Calc: 5.4
  DateTime::Format::Strptime: 1.07
  Email::Valid: 0.15
  Email::Valid::Loose: 0.04
  Time::Piece: 1.15
  Validator::Custom: 0.1208
resources:
  license: http://dev.perl.org/licenses/
version: 0.0612
