---
name: Validator-Custom-HTMLForm
version: 0.0301
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: HTML Form validator based on Validator::Custom
license: perl
resources:
  license: ~
requires:
  Date::Calc: 5.4
  DateTime::Format::Strptime: 1.07
  Email::Valid: 0.15
  Email::Valid::Loose: 0.04
  Time::Piece: 1.15
  Validator::Custom: 0.0301
  Validator::Custom::Trim: 0.0301
build_requires:
  Test::More: 0
provides:
  Validator::Custom::HTMLForm:
    file: lib/Validator/Custom/HTMLForm.pm
    version: 0.0301
  Validator::Custom::HTMLForm::Constraints:
    file: lib/Validator/Custom/HTMLForm.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
